import io

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER 

def generate_txt_content(title, author, date, summary_text):
    """Generates a formatted string for TXT export."""
    return f"""==================================================
BOOK SUMMARY REPORT
==================================================

Title:  {title}
Author: {author or 'Unknown'}
Date:   {date}

==================================================
SUMMARY
==================================================

{summary_text}

==================================================
Generated by Book Summarizer AI
"""

def generate_pdf_content(title, author, date, summary_text):
    """Generates a PDF file in memory using ReportLab."""
    buffer = io.BytesIO()
    
    # 1. Setup Document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=72
    )
    
    # 2. Define Styles
    styles = getSampleStyleSheet()
    
    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.fontSize = 18
    title_style.spaceAfter = 12

    meta_style = ParagraphStyle(
        'Meta',
        parent=styles['Normal'],
        fontSize=10,
        textColor='grey',
        alignment=TA_CENTER,
        spaceAfter=30
    )

    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=11,
        leading=14,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )

    # 3. Build Content
    story = []
    
    # Header
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"Author: {author or 'Unknown'} | Date: {date}", meta_style))
    story.append(Spacer(1, 12))
    
    # Summary Content (Handle paragraphs)
    paragraphs = summary_text.split('\n')
    for para in paragraphs:
        if para.strip():
            story.append(Paragraph(para, body_style))
    
    # Footer
    story.append(Spacer(1, 24))
    footer_style = ParagraphStyle('Footer', parent=meta_style, fontSize=8)
    story.append(Paragraph("Generated by Book Summarizer AI", footer_style))

    # 4. Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer